# Generated by Django 3.1.2 on 2020-10-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201028_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docsisupdate',
            old_name='lang',
            new_name='language',
        ),
    ]
