# Generated by Django 3.1.2 on 2020-10-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201028_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableModem',
            fields=[
                ('modem_macaddr', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ipaddr', models.CharField(max_length=16, unique=True)),
                ('cmts_ip', models.CharField(max_length=16)),
                ('agentid', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=5)),
                ('mce_concat', models.CharField(blank=True, max_length=3, null=True)),
                ('mce_ver', models.CharField(blank=True, max_length=4, null=True)),
                ('mce_frag', models.CharField(blank=True, max_length=3, null=True)),
                ('mce_phs', models.CharField(blank=True, max_length=3, null=True)),
                ('mce_igmp', models.CharField(blank=True, max_length=3, null=True)),
                ('mce_bpi', models.CharField(blank=True, max_length=4, null=True)),
                ('mce_ds_said', models.PositiveIntegerField(blank=True, null=True)),
                ('mce_us_sid', models.PositiveIntegerField(blank=True, null=True)),
                ('mce_filt_dot1p', models.CharField(blank=True, max_length=3, null=True)),
                ('mce_filt_dot1q', models.CharField(blank=True, max_length=3, null=True)),
                ('mce_tetps', models.PositiveIntegerField(blank=True, null=True)),
                ('mce_ntet', models.PositiveIntegerField(blank=True, null=True)),
                ('mce_dcc', models.CharField(blank=True, max_length=3, null=True)),
                ('thetime', models.DateTimeField()),
                ('offer_time', models.DateTimeField(blank=True, null=True)),
                ('ack_time', models.DateTimeField(blank=True, null=True)),
                ('net_id', models.PositiveSmallIntegerField()),
                ('cluster_id', models.PositiveSmallIntegerField()),
                ('ra_id', models.PositiveSmallIntegerField()),
                ('vsi_devtype', models.CharField(max_length=255)),
                ('vsi_esafetypes', models.CharField(max_length=255)),
                ('vsi_serialno', models.CharField(max_length=255)),
                ('vsi_hwver', models.CharField(max_length=255)),
                ('vsi_swver', models.CharField(max_length=255)),
                ('vsi_bootrom', models.CharField(max_length=255)),
                ('vsi_oui', models.CharField(max_length=255)),
                ('vsi_model', models.CharField(max_length=255)),
                ('vsi_vendor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'docsis_update',
            },
        ),
        migrations.DeleteModel(
            name='DocsisUpdate',
        ),
    ]
